<?php
/*
Plugin Name: Blood Bowl League Manager Widgits
Plugin URI: http://www.hdwsbbl.co.uk/
Description: All the widgets generated by the BBLM system
Author: Blacksnotling
Version: 1.2
Author URI: http://www.blacksnotling.com/
*/

/*
*	Filename: bb.widgit.core.php
*	Version: 0.1b
*	Description: File contains all the widgits related to the BBLM (not theme specific).
*/
/* -- Change History --
20080314 - 0.1b - Initial creation of file with recent matches widgit.
20080318 - 0.2b - Recent matches widget finished (1st draft).
20080429 - 0.3b - repaced dev_posts with '.$wpdb->posts.'
20080730 - 1.0 - bump to Version 1 for public release.
20090330 - 1,1 - Editied to filter out non hdwsbbl details
20100123 - 1.2 - Updated the prefix for the custom bb tables in the Database (tracker [224])

*/
function widget_bblm_recentmatches_init() {

	if ( !function_exists('register_sidebar_widget') )
		return;
	function widget_bblm_recentmatches($args) {
	global $wpdb;

		$options = get_option('widget_bblm_recentmatches');
		$nummatches = htmlspecialchars($options['nummatch'], ENT_QUOTES);
		$showfun = htmlspecialchars($options['showfun'], ENT_QUOTES);

		extract($args);
		$options = get_option('widget_bblm_recentmatches');
		$title = $options['title'];
		$nummatch = $options['nummatch'];
		$showfun = $options['showfun'];

		// These lines generate our output. Widgets can be very complex
		// but as you can see here, they can also be very, very simple.

		echo $before_widget . $before_title . $title . $after_title;
		?>

		<?php
$matchsql = "SELECT M.m_date, T.t_name AS tA, Q.t_name AS tB, M.m_teamAtd, M.m_teamBtd, M.m_gate, P.guid FROM ".$wpdb->prefix."match M, ".$wpdb->prefix."bb2wp J, ".$wpdb->posts." P, ".$wpdb->prefix."team T, ".$wpdb->prefix."team Q, ".$wpdb->prefix."comp C WHERE C.c_id = M.c_id AND M.m_id = J.tid AND J.pid = P.ID AND J.prefix = 'm_' AND M.m_teamA = T.t_id AND C.c_show = 1 AND C.type_id = 1 AND M.m_teamB = Q.t_id";
//If the "show all" matches option was not selcted then restrict
if (FALSE === $showfun) {
	$matchsql .=" AND C.c_counts = '1'";
}
$matchsql .= " ORDER BY m_date DESC, m_id DESC LIMIT ".$nummatches;

if ($matches = $wpdb->get_results($matchsql)) {
	print("<ul>\n");
	foreach ($matches as $match) {
		print("  <li><a href=\"".$match->guid."\" title=\"View the match in detail\">".$match->tA." <strong>".$match->m_teamAtd."</strong> vs <strong>".$match->m_teamBtd."</strong> ".$match->tB."</a></li>");
	}
	print("</ul>\n");
}

		?>


		<?php
		echo $after_widget;
	}

	function widget_bblm_recentmatches_control() {

		$options = get_option('widget_bblm_recentmatches');
		if ( !is_array($options) )
			$options = array('title'=>'', 'nummatch'=>'');
		if ( $_POST['bblm_rm-submit'] ) {

			$options['title'] = strip_tags(stripslashes($_POST['bblm_rm-title']));
			$options['nummatch'] = strip_tags(stripslashes($_POST['bblm_rm-number']));
			$options['showfun'] = strip_tags(stripslashes($_POST['bblm_rm-showfun']));
			update_option('widget_bblm_recentmatches', $options);
		}

		$title = htmlspecialchars($options['title'], ENT_QUOTES);
		$nummatches = htmlspecialchars($options['nummatch'], ENT_QUOTES);
		$showfun = htmlspecialchars($options['showfun'], ENT_QUOTES);

				echo '<p style="text-align:right;"><label for="bblm_rm-title">' . __('Title:') . ' <input style="width: 200px;" id="bblm_rm-title" name="bblm_rm-title" type="text" value="'.$title.'" /></label></p>';
		echo '<p style="text-align:right;"><label for="bblm_rm-number">' . __('number to show:') . ' <input style="width: 35px;" id="bblm_rm-number" name="bblm_rm-number" type="text" value="'.$nummatches.'"/></label></p>';
		echo '<p style="text-align:right;"><label for="bblm_rm-showfun">' . __('Show "Fun" Comps?:') . ' <input style="width: 35px;" id="bblm_rm-showfun" name="bblm_rm-showfun" type="text" value="'.$showfun.'"/></label> (1=Y,0=N)</p>';
		echo '<input type="hidden" id="bblm_rm-submit" name="bblm_rm-submit" value="1" />';
	}







	register_sidebar_widget(array('bblm_recentmatches', 'widgets'), 'widget_bblm_recentmatches');
	register_widget_control(array('bblm_recentmatches', 'widgets'), 'widget_bblm_recentmatches_control', 300, 100);
}


// Run our code later in case this loads prior to any required plugins.
add_action('widgets_init', 'widget_bblm_recentmatches_init');